### ISSUE TITLE
Geojson import issue

### ISSUE THREAD

**Issue by mbolli** [timelinize/timelinize#23]
I can't import a geojson with the following log entry (unfortunately the frontend does not show that it did not work), and then it crashes:

```log
{"level":"info","ts":1723822701.2949479,"msg":"decoding object: json: cannot unmarshal array into Go struct field .geometry.coordinates of type float64"}
```

Heres how the geojson begins:

```json
{"type":"FeatureCollection","features":[{
  "type":"Feature","properties":{},"geometry":{
    "type":"LineString","coordinates":[
       [7.243329,47.127258,1624659753],
       ...
     ]
  }
}
```

**Comment by rubiojr** [comment]
I haven't looked into this, but that third array element is supposed to be optional and mean altitude above sea level in meters (I think?), but isn't it crazy high 🏔️? Maybe the parser does not accept that optional height?

**Comment by mholt** [comment]
That's very interesting. I only have the "Point" type implemented currently (as that's all I encountered myself), but before I can even check that, the JSON decoding fails because the `Coordinates` field is a `[]float64` not a `[][]float64`.

I can fairly easily add support for LineString, but the big question is what to do about that third element. Like @rubiojr said, it's way too big for an altitude and is almost certainly a timestamp. Where did this data come from? It does not seem to be standards-compliant.

That said, maybe if the altitude is higher than Everest (or lower than we can try interpreting it as a timestamp). I'd be curious if there's any relevant GeoJSON that dates back to timestamps that are ambiguous with valid elevations in meters, but that's the problems you encounter when software deviates from spec...

**Comment by mbolli** [comment]
Actually, what comes after the coordinates is not defined:

> [3.1.4](https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.4).  LineString
> 
>    For type "LineString", the "coordinates" member is an array of two or
>    more positions.

I encountered geojson with the third argument as timestamp, and altitude as the forth, precision as the fifth (I am the author of [php-geobuf](https://github.com/mbolli/php-geobuf), a fork of pygeobuf.

But this obviously makes it difficult for timelinize to parse. Without date the information is basically useless.

**Comment by rubiojr** [comment]
> Actually, what comes after the coordinates is not defined:
> 
> 3.1.4. LineString
> 
> For type "LineString", the "coordinates" member is an array of two or
> more positions.

Correct me if I'm wrong @mbolli, but that does not say the third element of an array (position/point) is not defined, it's saying a line is meant to be defined by at least two points (or two arrays of two floats each).

The RFC reads when [defining geojson coordinates](https://datatracker.ietf.org/doc/html/rfc7946#section-4):

> An OPTIONAL third-position element SHALL be the height in meters above or below the WGS 84 reference ellipsoid.  In the absence of elevation values, applications sensitive to height or depth SHOULD interpret positions as being at local ground or sea level.

I'm far from a GeoJSON expert though, not discarding my reading is incorrect 😃

**Comment by mholt** [comment]
I think that's correct @rubiojr. It's confusing because there's arrays of arrays but it depends on the type of the geometry.

@mbolli That's very peculiar. I can try to be flexible and accept the non standard compliant input as long as altitudes and timestamps aren't close to each other in magnitude. But mileage may vary 😅

**Comment by mbolli** [comment]
@rubiojr of course you're right. Guess I should buy new glasses ;)

In 3.1.1 it states:

>    A position is an array of numbers.  There MUST be two or more
>    elements.  The first two elements are longitude and latitude, or
>    easting and northing, precisely in that order and using decimal
>    numbers.  Altitude or elevation MAY be included as an optional third
>    element.

> 
Implementations SHOULD NOT extend positions beyond three elements because the semantics of extra elements are unspecified and ambiguous. Historically, some implementations have used a fourth element to carry a linear referencing measure (sometimes denoted as "M") or a numerical timestamp, but in most situations a parser will not be able to properly interpret these values. The interpretation and meaning of additional elements is beyond the scope of this specification, and additional elements MAY be ignored by parsers.

**Comment by mholt** [comment]
Ha, Yeah I also find the spec confusing!

> As most peoples online lifes did not start until 1990, everything under could be altitude?

That's a good point 😄 but, I am thinking of the cases where historical data may be encoded as GeoJSON. Even if data generated by modern apps as we know today won't have timestamps before 199x and more likely even 200x, if a program that has historical map data exports it into GeoJSON, I could easily see dates that look like altitudes.

But yeah, I'm torn since the source of this data is clearly in violation of the spec, but where it's fairly easy (like checking what the numeric value is) I wouldn't mind accommodating.

**Comment by mholt** [comment]
I'm labeling this as a bug since I found and fixed an actual bug while working on this.

@mbolli I've pushed a commit that allows Timelinize to decode non-spec-compliant data like yours if the 3rd and 4th elements exist in a position and they are altitude or timestamp (we guess based on numeric magnitude). This requires that the data source option `Lenient` is set to `true`. I haven't exposed this in the UI yet (anyone want to practice a PR to add it? Do it in includes/modals.html and modals.js -- those are where the data source options are for the UI). So if you clone down the latest and just hard-code `Lenient` to true (or modify the HTTP request made by the UI) then you could test this.

I haven't actually any real GeoJSON data sets to test with, only a sample with 7 points 😅  -- so if you could please try it out then that would be super helpful!

One comment I almost missed:

> But this obviously makes it difficult for timelinize to parse. Without date the information is basically useless.

Agreed, however, date information is not _only_ in the position element. The sample data I found had it in the `Feature/Properties` object. There's `time` and `time_long` fields. It's not in the spec but the spec doesn't define what the properties must be. I just assumed that's common from the sample I obtained.

But yeah, timestamp is valuable enough that if it's in with each point -- that's ideal -- we want to get it :100:
