### ISSUE TITLE
geojson: Doesn't capture metadata liberally

### ISSUE THREAD

**Issue by rubiojr** [timelinize/timelinize#32]
The Metadata section in the rendered Item view is empty for some known items (tested media and geojson):

![Image](https://github.com/user-attachments/assets/d682342f-2b04-482e-bf4e-c5aaa913d79e)

![Image](https://github.com/user-attachments/assets/e2457d42-3aa7-449c-a5f7-f9d4fc0821bd)

I'm not sure if the intention is for that metadata section to render the arbitrary [Metadata from an Item](https://github.com/timelinize/timelinize/blob/d159313ec9e5290a0f534bf3da480fc4833484e1/timeline/itemgraph.go#L217) or something else.

Could it be that the two items that imported lack the required Metadata fields to be displayed? The Photo has a bunch of regular exif fields, and the GeoJSON looks like:

```json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          23.72061805150883,
          37.980743408203125
        ]
      },
      "properties": {
        "Country": "Greece",
        "ISO Country": "GR",
        "Name": "Panagi Tsaldari 55",
        "Timestamp": 1722674930.7632985
      }
    }
    ]
```

**Comment by rubiojr** [comment]
> Could it be that the two items that imported lack the required Metadata fields to be displayed?

That seems to be the case, at least for the geojson object, not sure why the picture doesn't render any metadata. I added an additional property `provider` to the geojson object and it's rendered as intended.

![Image](https://github.com/user-attachments/assets/a25f239b-7cba-4485-8ed4-bbc5b2891393)

Given that (from [the spec](https://datatracker.ietf.org/doc/html/rfc7946#section-3.2)):

> A Feature object has a member with the name "properties". The value of the properties member is an object (any JSON object or a JSON null value). 

I incorrectly assumed that every feature property would be rendered in the Metadata section, but that sees to be limited to the ones defined in https://github.com/timelinize/timelinize/blob/d159313ec9e5290a0f534bf3da480fc4833484e1/datasources/geojson/geojson.go#L313.

This would be geojson specific, but since an arbitrary json object can be the properties, should we accept arbitrary properties ( a `map[string]any` perhaps) and store/render them?

**Comment by rubiojr** [comment]
related: https://github.com/timelinize/timelinize/pull/33

**Comment by rubiojr** [comment]
Closing this, the issue description isn't very accurate. Timelinize does render metadata available in `Item`, but it's the data source responsibility to save it.

**Comment by mholt** [comment]
Nevermind, you already submitted a PR. Not sure how I didn't see it until now. Awesome!!

**Comment by mholt** [comment]
@rubiojr According to my limited testing, bc5c07d706f3b1b907d5c21d4c1fb0088d3c7e33 should now let us accept any field in Properties and keep it as metadata, while extracting certain information we treat first-class like time, altitude, etc., or which we standardize like heading and velocity. I also thought to accept several timestamp formats since we really just won't know for sure.

I haven't much data to test with though, so if you could it through your data that would be fantastic!

As for the photo above that doesn't have metadata: does it have any EXIF data? If not, I don't think it will have metadata. If it does have EXIF, can you show a screenshot with at least a sample of it? It could be that our EXIF library does not support that particular image for some reason, but I don't know a lot about it. If that is the case, uploading the original image file here could be helpful (if you don't mind -- feel free to alter any location data if desired).

**Comment by rubiojr** [comment]
@mholt it's working pretty great. Caught a couple of minor issues, opened https://github.com/timelinize/timelinize/pull/35.
