### ISSUE TITLE
Collaboration with Immich?

### ISSUE THREAD

**Issue by aviv926** [timelinize/timelinize#49]
This looks like a great project, in fact I've seen the project history and it looks like it could work great with Immich in terms of pulling photos taken along today's timeline (as [Google does a timeline integration with Google Photos](https://www.gadgets360.com/apps/news/google-photos-maps-timeline-update-adds-new-feature-picture-routes-2339967))
immich has an [API interface](https://immich.app/docs/api) that I think with the right combination it could work just great and then it would be the excellent alternative as you presented in the history of this project.

> I've been working on this project since about 2013, even before I conceptualized [Caddy](https://caddyserver.com/). My initial vision was to create an automated backup of my Picasa albums that I could store on my own hard drive. This project was called Photobak. Picasa eventually became Google Photos, and about the same time I realized I wanted to backup my photos posted to Facebook, Instagram, and Twitter, too. And while I was at it, why not include my Google Location History to augment the location data from the photos. The vision continued to expand as I realized that my family could use this too, so the schema was upgraded to support multiple people/entities as well. This could allow us to merge databases, or timelines, as family members pass, or as they share parts of their timeline around with each other. Timelinize is the mature evolution of the original project that is now designed to be a comprehensive, highly detailed archive of one's life through digital (or digitized) content. An authoritative, unified record that is easy to preserve and organize.

**Comment by mholt** [comment]
Heya, thanks for writing in!

I like Immich a lot. Been following their Discord on and off for a while now.

Anyway, I think Immich could make a good _data source_ for Timelinize, as does any other photo library like Google Photos (already implemented), Photostructure, Ente, NextCloud/OwnCloud, etc. This way, people can keep using their photo library of choice (at least until Timelinize has competitive photo management features), and just import into Timelinize every so often.

**Comment by aviv926** [comment]
Maybe it can be automatic with their API interface? So it could save development on adding an image manager?

Although you might want to make your project all in one...

**Comment by mholt** [comment]
If by "automatic with their API interface," you mean the ability for Immich (or something outside of Timelinize, like a script) to be able to add data to Timelinize without us writing an Immich data source, that kind of "push" model is being planned/discussed in #31.

> Although you might want to make your project all in one...

I am indeed hoping for Timelinize to ultimately be a great photo library too. Right now, the priority is to stabilize getting data into the repository, then we can flush out the UI and other features more. :+1:

Really appreciate this idea and discussion. Willing to discuss more, but I'll close this for now since there's nothing particularly actionable from what I can see. Feel free to continue discussion though and we can reopen if needed!
