### ISSUE TITLE
Support remote data sources

### ISSUE THREAD

**Issue by xathon** [timelinize/timelinize#60]
As an example, I use Immich for my photo management. If I were to host Timelinize on the same system and wanted to import my photos (from Immich or Google, whatever), currently, it would store the photos twice on the same system, which would waste storage space. I'd like to instead be able to import a URL to e.g. a picture (e.g. https://immich.mydomain.com/api/assets/URI/thumbnail)

This probably depends on #31 , as you wouldn't really get the data in this format otherwise.

**Comment by mholt** [comment]
Great thoughts!

So there's actually 2 requests here.

> As an example, I use Immich for my photo management. 

Adding support for Immich / PhotoPrism / PhotoStructure are all on my list, in fact (I just haven't made issues for them yet) -- I think it makes a lot of sense to support self-hosted photo libraries!

>  it would store the photos twice on the same system, which would waste storage space. I'd like to instead be able to import a URL to e.g. a picture

As for this, that is way more nuanced and tricky with relation to the goals for this project... I've thought about this a lot, because I know some people will really want this, but it's so tricky. PhotoStructure is one project that is trying to keep the photo files in their original places. There's a LOT of work involved with keeping track of them.

What if the file is renamed or moved? What if it is changed? How do you determine what kind of change was made? Was it intentional? How do you keep integrity checks in line with intentional changes? How do you move your Timeline if all the files are scattered everywhere, even on external storage?

There's a lot of benefits to and goals for the project that fall apart if the file is not in the Timelinize repository and under Timelinize's control...

Anyway, as it stands, I am not sure if pointing to an external file as the source of truth for an item is feasible for this project.

I welcome more discussion on this! But I might close this issue for now, since I don't foresee acting on it unless we can figure out a way to solve all the problems with the approach.

However, new issues could be opened for support for specific data sources, if you'd be interested in doing that.
